// SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: MPL-2.0

package rdb

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/noi-techpark/opendatahub-go-sdk/ingest/urn"
	"github.com/noi-techpark/opendatahub-go-sdk/tel"
	httptel "github.com/noi-techpark/opendatahub-go-sdk/tel/http"
	"go.opentelemetry.io/otel/trace"
)

type RawAny = Raw[any]

// raw data message as generated by data collectors and stored in the mongodb
type Raw[Rawtype any] struct {
	Provider    string    `json:"provider"`
	Timestamp   time.Time `json:"timestamp"`
	Rawdata     Rawtype   `json:"rawdata"`
	ContentType string    `json:"content_type"`

	// Meta carries publisher-set fields that are not part of the payload.
	//
	// On the way out they travel as X-OpenDataHub-<name> headers; the raw writer
	// strips that prefix, lowercases what is left, and stores the result in the
	// document's `meta` sub-document — which is also where it is read back from.
	// Use lowercase keys, since that is what comes back regardless of what was
	// sent.
	//
	// This is the only place a collector can put a field the database is able to
	// group on, which is what makes keyed lookups (RDBridge.GetCompacted) possible
	// without reaching into the payload.
	Meta map[string]string `json:"meta,omitempty"`
}

var (
	ErrDocumentNotFound = errors.New("document not found")

	// ErrCollectionNotFound means the collection does not exist, which is a
	// different fact from it being empty. A consumer that treats the two alike
	// cannot see a typo in its own configuration: it builds an empty table and
	// reports success.
	ErrCollectionNotFound = errors.New("collection not found")
	ErrBadURN             = errors.New("bad urn format")
	ErrBadRequest         = errors.New("bad request")
	ErrServerErr          = errors.New("internal server error")
)

type Env struct {
	RAW_DATA_BRIDGE_ENDPOINT string
}

type RDBridge struct {
	endpoint string
}

func NewRDBridge(config Env) *RDBridge {
	return &RDBridge{
		endpoint: strings.TrimRight(config.RAW_DATA_BRIDGE_ENDPOINT, "/"),
	}
}

func (b RDBridge) Get(ctx context.Context, urn *urn.URN) ([]byte, error) {
	// Start a new client span for the outbound HTTP request.
	// this uses GlobalTelemetry
	ctx, clientSpan := tel.TraceStart(
		ctx,
		fmt.Sprintf("HTTP GET /urns/%s", urn.String()),
		trace.WithSpanKind(trace.SpanKindClient),
	)
	defer clientSpan.End()

	// Create a new request with the provided context (which now carries the client span).
	req, err := http.NewRequestWithContext(ctx, "GET", fmt.Sprintf("%s/urns/%s", b.endpoint, urn.String()), nil)
	if err != nil {
		tel.OnError(ctx, "failed to create request", err)
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Use your HTTP client that injects trace context.
	httpClient := httptel.NewHttpTelClient()
	resp, err := httpClient.Do(req)
	if err != nil {
		tel.OnError(ctx, "failed to get raw data", err)
		return nil, fmt.Errorf("failed to get raw data: %s", err.Error())
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusNotFound {
		return nil, ErrDocumentNotFound
	}
	if resp.StatusCode == http.StatusBadRequest {
		return nil, ErrBadURN
	}
	if resp.StatusCode != http.StatusOK {
		return nil, ErrServerErr
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		tel.OnError(ctx, "failed to read raw data body", err)
		return nil, fmt.Errorf("failed to read raw data body: %s", err.Error())
	}
	return body, nil
}

// Page is one page of a collection view. Items are whole documents, undecoded:
// their layout is the publisher's choice — identifying fields at the root, the
// payload in `rawdata`, possibly base64-encoded — so the client does not presume
// a shape.
//
// Next is empty when the walk is complete. It is opaque: the bridge derives it
// beside the ordering that produced it, so hand back the previous page's Next
// unchanged and do not attempt to construct one. A cursor issued for one
// ordering is refused by any other with 400.
type Page struct {
	Items []json.RawMessage
	Next  string
}

// CompactedQuery addresses the compacted view of a raw data collection: the
// newest document for every distinct value of a field under `meta`.
type CompactedQuery struct {
	DB         string
	Collection string
	// Field names a field inside the stored document's `meta` sub-document,
	// which the bridge groups on. Not a path, and not a field at the document
	// root: a payload posted as application/json is stored as a string, so
	// nothing inside it can be grouped on, and the rest of the root belongs to
	// the writer. A collector sets it by sending an X-OpenDataHub-<Field>
	// header.
	Field  string
	Cursor string
	Limit  int
}

// DocumentsQuery addresses a collection's log: every revision, newest written
// first.
type DocumentsQuery struct {
	DB         string
	Collection string
	Cursor     string
	Limit      int
}

type envelope struct {
	Field string            `json:"field"`
	Count int               `json:"count"`
	Next  string            `json:"next"`
	Data  []json.RawMessage `json:"data"`
}

func (b RDBridge) getPage(ctx context.Context, span, path string, params url.Values) (Page, error) {
	target := b.endpoint + path
	if q := params.Encode(); q != "" {
		target += "?" + q
	}

	ctx, clientSpan := tel.TraceStart(ctx, "HTTP GET "+span, trace.WithSpanKind(trace.SpanKindClient))
	defer clientSpan.End()

	req, err := http.NewRequestWithContext(ctx, "GET", target, nil)
	if err != nil {
		tel.OnError(ctx, "failed to create request", err)
		return Page{}, fmt.Errorf("failed to create request: %w", err)
	}

	resp, err := httptel.NewHttpTelClient().Do(req)
	if err != nil {
		tel.OnError(ctx, "failed to get raw data page", err)
		return Page{}, fmt.Errorf("failed to get raw data page: %w", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
	case http.StatusBadRequest:
		return Page{}, fmt.Errorf("%w: GET %s", ErrBadRequest, path)
	case http.StatusNotFound:
		return Page{}, fmt.Errorf("%w: GET %s", ErrCollectionNotFound, path)
	default:
		return Page{}, fmt.Errorf("%w: status %d", ErrServerErr, resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		tel.OnError(ctx, "failed to read raw data page", err)
		return Page{}, fmt.Errorf("failed to read raw data page: %w", err)
	}
	var env envelope
	if err := json.Unmarshal(body, &env); err != nil {
		return Page{}, fmt.Errorf("failed to unmarshal raw data page: %w", err)
	}
	return Page{Items: env.Data, Next: env.Next}, nil
}

func paging(cursor string, limit int) url.Values {
	params := url.Values{}
	if cursor != "" {
		params.Set("cursor", cursor)
	}
	if limit > 0 {
		params.Set("limit", strconv.Itoa(limit))
	}
	return params
}

// GetCompacted fetches one page of a collection's compacted view.
//
// Walking every page yields the current value of every key, which is the whole
// of a reference table. Reconciling means walking again: the walk is the entire
// state, so a re-read cannot miss a change however it was written or dated.
func (b RDBridge) GetCompacted(ctx context.Context, q CompactedQuery) (Page, error) {
	path := fmt.Sprintf("/%s/%s/compacted/%s",
		url.PathEscape(q.DB), url.PathEscape(q.Collection), url.PathEscape(q.Field))
	return b.getPage(ctx, path, path, paging(q.Cursor, q.Limit))
}

// GetDocuments fetches one page of a collection's log, newest written first.
//
// "Newest" is write order, not the publisher's timestamp: a backfill is written
// now and dated whenever the collector chose, so it leads the list carrying an
// old timestamp.
func (b RDBridge) GetDocuments(ctx context.Context, q DocumentsQuery) (Page, error) {
	path := fmt.Sprintf("/%s/%s/documents",
		url.PathEscape(q.DB), url.PathEscape(q.Collection))
	return b.getPage(ctx, path, path, paging(q.Cursor, q.Limit))
}

// GetLastDocument returns the most recently written document in a collection, or
// ErrDocumentNotFound if there is none. The collection still has to exist.
func (b RDBridge) GetLastDocument(ctx context.Context, db, collection string) (json.RawMessage, error) {
	page, err := b.GetDocuments(ctx, DocumentsQuery{DB: db, Collection: collection, Limit: 1})
	if err != nil {
		return nil, err
	}
	if len(page.Items) == 0 {
		return nil, ErrDocumentNotFound
	}
	return page.Items[0], nil
}

func Get[P any](rdb *RDBridge, ctx context.Context, urn *urn.URN) (Raw[P], error) {
	body, err := rdb.Get(ctx, urn)
	if err != nil {
		return Raw[P]{}, err
	}
	var r Raw[P]
	err = json.Unmarshal(body, &r)
	if err != nil {
		return Raw[P]{}, fmt.Errorf("failed to unmarshal raw data: %s", err.Error())
	}

	return r, nil
}
